name: igw-ci-cd
on: [push]
jobs:
  deploy_dev:
    name: deploy_dev
    environment: development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: horochx/deploy-via-scp@master
      with:
        local: code/*
        remote: /var/www/html/
        host: ${{ secrets.DEV_HOST }} 
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }} 

  deploy_prod:
    name: deploy_prod
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: horochx/deploy-via-scp@master
      with:
        local: code/* 
        remote: /var/www/html/
        host: ${{ secrets.PROD_HOST }} 
        port: ${{ secrets.PORT }} 
        user: ${{ secrets.USERNAME }} 
        key: ${{ secrets.PRIVATE_KEY }} 